// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  threadId: __t.u64().name("thread_id"),
  senderId: __t.u64().name("sender_id"),
  receiverId: __t.u64().name("receiver_id"),
  senderEphemeralPubkey: __t.byteArray().name("sender_ephemeral_pubkey"),
  nonce: __t.byteArray(),
  ciphertext: __t.byteArray(),
  sentAt: __t.timestamp().name("sent_at"),
});
