// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  pairKey: __t.string().name("pair_key"),
  userLowId: __t.u64().name("user_low_id"),
  userHighId: __t.u64().name("user_high_id"),
  createdAt: __t.timestamp().name("created_at"),
  lastMessageAt: __t.timestamp().name("last_message_at"),
});
