// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  uploaderId: __t.u64().name("uploader_id"),
  filename: __t.string(),
  contentType: __t.string().name("content_type"),
  data: __t.byteArray(),
  size: __t.u64(),
  uploadedAt: __t.timestamp().name("uploaded_at"),
});
