// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.1 (commit a4d29daec8ed35ce4913a335b7210b9ae3933d00).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddReactionReducer from "./add_reaction_reducer";
import CreateCategoryReducer from "./create_category_reducer";
import CreateChannelReducer from "./create_channel_reducer";
import CreateInviteReducer from "./create_invite_reducer";
import CreateServerReducer from "./create_server_reducer";
import DeleteCategoryReducer from "./delete_category_reducer";
import DeleteChannelReducer from "./delete_channel_reducer";
import DeleteDmMessageReducer from "./delete_dm_message_reducer";
import DeleteFileReducer from "./delete_file_reducer";
import DeleteMessageReducer from "./delete_message_reducer";
import DeleteServerReducer from "./delete_server_reducer";
import JoinDmCallReducer from "./join_dm_call_reducer";
import JoinServerReducer from "./join_server_reducer";
import JoinVoiceChannelReducer from "./join_voice_channel_reducer";
import LeaveDmCallReducer from "./leave_dm_call_reducer";
import LeaveServerReducer from "./leave_server_reducer";
import LeaveVoiceChannelReducer from "./leave_voice_channel_reducer";
import LoginReducer from "./login_reducer";
import LogoutReducer from "./logout_reducer";
import OpenDmThreadReducer from "./open_dm_thread_reducer";
import RegisterReducer from "./register_reducer";
import RemoveAvatarReducer from "./remove_avatar_reducer";
import RemoveReactionReducer from "./remove_reaction_reducer";
import SendAudioFrameReducer from "./send_audio_frame_reducer";
import SendChannelMessageReducer from "./send_channel_message_reducer";
import SendDmAudioFrameReducer from "./send_dm_audio_frame_reducer";
import SendDmMessageReducer from "./send_dm_message_reducer";
import SendDmVideoFrameReducer from "./send_dm_video_frame_reducer";
import SendVideoFrameReducer from "./send_video_frame_reducer";
import SetChannelMediaSettingsReducer from "./set_channel_media_settings_reducer";
import SetPublicEncryptionKeyReducer from "./set_public_encryption_key_reducer";
import UpdateAvatarReducer from "./update_avatar_reducer";
import UpdateProfileReducer from "./update_profile_reducer";
import UploadFileReducer from "./upload_file_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AudioFrameEventRow from "./audio_frame_event_table";
import CategoryRow from "./category_table";
import ChannelRow from "./channel_table";
import ChannelMediaSettingsRow from "./channel_media_settings_table";
import ChannelMessageRow from "./channel_message_table";
import DmAudioFrameEventRow from "./dm_audio_frame_event_table";
import DmCallMemberRow from "./dm_call_member_table";
import DmMemberRow from "./dm_member_table";
import DmMessageRow from "./dm_message_table";
import DmThreadRow from "./dm_thread_table";
import DmVideoFrameEventRow from "./dm_video_frame_event_table";
import FileUploadRow from "./file_upload_table";
import InviteLinkRow from "./invite_link_table";
import MessageReactionRow from "./message_reaction_table";
import ServerRow from "./server_table";
import ServerMemberRow from "./server_member_table";
import UserAccountRow from "./user_account_table";
import UserSessionRow from "./user_session_table";
import VideoFrameEventRow from "./video_frame_event_table";
import VoiceMemberRow from "./voice_member_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  audio_frame_event: __table({
    name: 'audio_frame_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, AudioFrameEventRow),
  category: __table({
    name: 'category',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'category_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CategoryRow),
  channel: __table({
    name: 'channel',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'channel_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChannelRow),
  channel_media_settings: __table({
    name: 'channel_media_settings',
    indexes: [
      { name: 'channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
    ],
    constraints: [
      { name: 'channel_media_settings_channel_id_key', constraint: 'unique', columns: ['channelId'] },
    ],
  }, ChannelMediaSettingsRow),
  channel_message: __table({
    name: 'channel_message',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'channel_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChannelMessageRow),
  dm_audio_frame_event: __table({
    name: 'dm_audio_frame_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, DmAudioFrameEventRow),
  dm_call_member: __table({
    name: 'dm_call_member',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dm_call_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DmCallMemberRow),
  dm_member: __table({
    name: 'dm_member',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dm_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DmMemberRow),
  dm_message: __table({
    name: 'dm_message',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dm_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DmMessageRow),
  dm_thread: __table({
    name: 'dm_thread',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'pair_key', algorithm: 'btree', columns: [
        'pairKey',
      ] },
    ],
    constraints: [
      { name: 'dm_thread_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'dm_thread_pair_key_key', constraint: 'unique', columns: ['pairKey'] },
    ],
  }, DmThreadRow),
  dm_video_frame_event: __table({
    name: 'dm_video_frame_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, DmVideoFrameEventRow),
  file_upload: __table({
    name: 'file_upload',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'file_upload_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FileUploadRow),
  invite_link: __table({
    name: 'invite_link',
    indexes: [
      { name: 'code', algorithm: 'btree', columns: [
        'code',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'invite_link_code_key', constraint: 'unique', columns: ['code'] },
      { name: 'invite_link_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InviteLinkRow),
  message_reaction: __table({
    name: 'message_reaction',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'message_reaction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MessageReactionRow),
  server: __table({
    name: 'server',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'server_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ServerRow),
  server_member: __table({
    name: 'server_member',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'server_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ServerMemberRow),
  user_account: __table({
    name: 'user_account',
    indexes: [
      { name: 'email', algorithm: 'btree', columns: [
        'email',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'username', algorithm: 'btree', columns: [
        'username',
      ] },
    ],
    constraints: [
      { name: 'user_account_email_key', constraint: 'unique', columns: ['email'] },
      { name: 'user_account_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'user_account_username_key', constraint: 'unique', columns: ['username'] },
    ],
  }, UserAccountRow),
  user_session: __table({
    name: 'user_session',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_session_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserSessionRow),
  video_frame_event: __table({
    name: 'video_frame_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, VideoFrameEventRow),
  voice_member: __table({
    name: 'voice_member',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'voice_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VoiceMemberRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_reaction", AddReactionReducer),
  __reducerSchema("create_category", CreateCategoryReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("create_invite", CreateInviteReducer),
  __reducerSchema("create_server", CreateServerReducer),
  __reducerSchema("delete_category", DeleteCategoryReducer),
  __reducerSchema("delete_channel", DeleteChannelReducer),
  __reducerSchema("delete_dm_message", DeleteDmMessageReducer),
  __reducerSchema("delete_file", DeleteFileReducer),
  __reducerSchema("delete_message", DeleteMessageReducer),
  __reducerSchema("delete_server", DeleteServerReducer),
  __reducerSchema("join_dm_call", JoinDmCallReducer),
  __reducerSchema("join_server", JoinServerReducer),
  __reducerSchema("join_voice_channel", JoinVoiceChannelReducer),
  __reducerSchema("leave_dm_call", LeaveDmCallReducer),
  __reducerSchema("leave_server", LeaveServerReducer),
  __reducerSchema("leave_voice_channel", LeaveVoiceChannelReducer),
  __reducerSchema("login", LoginReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("open_dm_thread", OpenDmThreadReducer),
  __reducerSchema("register", RegisterReducer),
  __reducerSchema("remove_avatar", RemoveAvatarReducer),
  __reducerSchema("remove_reaction", RemoveReactionReducer),
  __reducerSchema("send_audio_frame", SendAudioFrameReducer),
  __reducerSchema("send_channel_message", SendChannelMessageReducer),
  __reducerSchema("send_dm_audio_frame", SendDmAudioFrameReducer),
  __reducerSchema("send_dm_message", SendDmMessageReducer),
  __reducerSchema("send_dm_video_frame", SendDmVideoFrameReducer),
  __reducerSchema("send_video_frame", SendVideoFrameReducer),
  __reducerSchema("set_channel_media_settings", SetChannelMediaSettingsReducer),
  __reducerSchema("set_public_encryption_key", SetPublicEncryptionKeyReducer),
  __reducerSchema("update_avatar", UpdateAvatarReducer),
  __reducerSchema("update_profile", UpdateProfileReducer),
  __reducerSchema("upload_file", UploadFileReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

