// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AudioFrameEvent = __t.object("AudioFrameEvent", {
  channelId: __t.u64(),
  from: __t.identity(),
  seq: __t.u32(),
  sampleRate: __t.u32(),
  channels: __t.u8(),
  rms: __t.f32(),
  pcm16Le: __t.byteArray(),
});
export type AudioFrameEvent = __Infer<typeof AudioFrameEvent>;

export const Category = __t.object("Category", {
  id: __t.u64(),
  serverId: __t.u64(),
  name: __t.string(),
  position: __t.u32(),
});
export type Category = __Infer<typeof Category>;

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  serverId: __t.u64(),
  categoryId: __t.u64(),
  name: __t.string(),
  get channelType() {
    return ChannelType;
  },
  position: __t.u32(),
  createdAt: __t.timestamp(),
});
export type Channel = __Infer<typeof Channel>;

export const ChannelMediaSettings = __t.object("ChannelMediaSettings", {
  channelId: __t.u64(),
  audioTargetSampleRate: __t.u32(),
  audioFrameMs: __t.u16(),
  audioMaxFrameBytes: __t.u32(),
  audioBitrateKbps: __t.u32(),
  audioTalkingRmsThreshold: __t.f32(),
  videoEnabled: __t.bool(),
  videoWidth: __t.u16(),
  videoHeight: __t.u16(),
  videoFps: __t.u8(),
  videoJpegQuality: __t.f32(),
  videoMaxFrameBytes: __t.u32(),
});
export type ChannelMediaSettings = __Infer<typeof ChannelMediaSettings>;

export const ChannelMessage = __t.object("ChannelMessage", {
  id: __t.u64(),
  channelId: __t.u64(),
  senderId: __t.u64(),
  content: __t.string(),
  sentAt: __t.timestamp(),
});
export type ChannelMessage = __Infer<typeof ChannelMessage>;

// The tagged union or sum type for the algebraic type `ChannelType`.
export const ChannelType = __t.enum("ChannelType", {
  Text: __t.unit(),
  Voice: __t.unit(),
});
export type ChannelType = __Infer<typeof ChannelType>;

export const DmAudioFrameEvent = __t.object("DmAudioFrameEvent", {
  threadId: __t.u64(),
  from: __t.identity(),
  seq: __t.u32(),
  sampleRate: __t.u32(),
  channels: __t.u8(),
  rms: __t.f32(),
  pcm16Le: __t.byteArray(),
});
export type DmAudioFrameEvent = __Infer<typeof DmAudioFrameEvent>;

export const DmCallMember = __t.object("DmCallMember", {
  id: __t.u64(),
  threadId: __t.u64(),
  userId: __t.u64(),
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type DmCallMember = __Infer<typeof DmCallMember>;

export const DmMember = __t.object("DmMember", {
  id: __t.u64(),
  threadId: __t.u64(),
  userId: __t.u64(),
  joinedAt: __t.timestamp(),
});
export type DmMember = __Infer<typeof DmMember>;

export const DmMessage = __t.object("DmMessage", {
  id: __t.u64(),
  threadId: __t.u64(),
  senderId: __t.u64(),
  receiverId: __t.u64(),
  senderEphemeralPubkey: __t.byteArray(),
  nonce: __t.byteArray(),
  ciphertext: __t.byteArray(),
  sentAt: __t.timestamp(),
});
export type DmMessage = __Infer<typeof DmMessage>;

export const DmThread = __t.object("DmThread", {
  id: __t.u64(),
  pairKey: __t.string(),
  userLowId: __t.u64(),
  userHighId: __t.u64(),
  createdAt: __t.timestamp(),
  lastMessageAt: __t.timestamp(),
});
export type DmThread = __Infer<typeof DmThread>;

export const DmVideoFrameEvent = __t.object("DmVideoFrameEvent", {
  threadId: __t.u64(),
  from: __t.identity(),
  seq: __t.u32(),
  width: __t.u16(),
  height: __t.u16(),
  jpeg: __t.byteArray(),
});
export type DmVideoFrameEvent = __Infer<typeof DmVideoFrameEvent>;

export const FileUpload = __t.object("FileUpload", {
  id: __t.u64(),
  uploaderId: __t.u64(),
  filename: __t.string(),
  contentType: __t.string(),
  data: __t.byteArray(),
  size: __t.u64(),
  uploadedAt: __t.timestamp(),
});
export type FileUpload = __Infer<typeof FileUpload>;

export const InviteLink = __t.object("InviteLink", {
  id: __t.u64(),
  serverId: __t.u64(),
  code: __t.string(),
  createdBy: __t.u64(),
  maxUses: __t.u32(),
  uses: __t.u32(),
  createdAt: __t.timestamp(),
});
export type InviteLink = __Infer<typeof InviteLink>;

// The tagged union or sum type for the algebraic type `MemberRole`.
export const MemberRole = __t.enum("MemberRole", {
  Owner: __t.unit(),
  Admin: __t.unit(),
  Member: __t.unit(),
});
export type MemberRole = __Infer<typeof MemberRole>;

export const MessageReaction = __t.object("MessageReaction", {
  id: __t.u64(),
  messageId: __t.u64(),
  userId: __t.u64(),
  emoji: __t.string(),
  createdAt: __t.timestamp(),
});
export type MessageReaction = __Infer<typeof MessageReaction>;

export const Server = __t.object("Server", {
  id: __t.u64(),
  name: __t.string(),
  ownerId: __t.u64(),
  iconUrl: __t.string(),
  createdAt: __t.timestamp(),
});
export type Server = __Infer<typeof Server>;

export const ServerMember = __t.object("ServerMember", {
  id: __t.u64(),
  serverId: __t.u64(),
  userId: __t.u64(),
  get role() {
    return MemberRole;
  },
  joinedAt: __t.timestamp(),
});
export type ServerMember = __Infer<typeof ServerMember>;

export const UserAccount = __t.object("UserAccount", {
  id: __t.u64(),
  email: __t.string(),
  username: __t.string(),
  passwordHash: __t.string(),
  displayName: __t.string(),
  avatarUrl: __t.string(),
  createdAt: __t.timestamp(),
  publicEncryptionKey: __t.option(__t.byteArray()),
  status: __t.option(__t.string()),
  avatarFileId: __t.u64(),
  bannerFileId: __t.u64(),
});
export type UserAccount = __Infer<typeof UserAccount>;

export const UserSession = __t.object("UserSession", {
  identity: __t.identity(),
  userId: __t.u64(),
  connectedAt: __t.timestamp(),
});
export type UserSession = __Infer<typeof UserSession>;

export const VideoFrameEvent = __t.object("VideoFrameEvent", {
  channelId: __t.u64(),
  from: __t.identity(),
  seq: __t.u32(),
  width: __t.u16(),
  height: __t.u16(),
  jpeg: __t.byteArray(),
});
export type VideoFrameEvent = __Infer<typeof VideoFrameEvent>;

export const VoiceMember = __t.object("VoiceMember", {
  id: __t.u64(),
  channelId: __t.u64(),
  userId: __t.u64(),
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type VoiceMember = __Infer<typeof VoiceMember>;

