// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  email: __t.string(),
  username: __t.string(),
  passwordHash: __t.string().name("password_hash"),
  displayName: __t.string().name("display_name"),
  avatarUrl: __t.string().name("avatar_url"),
  createdAt: __t.timestamp().name("created_at"),
  publicEncryptionKey: __t.option(__t.byteArray()).name("public_encryption_key"),
  status: __t.option(__t.string()),
  avatarFileId: __t.u64().name("avatar_file_id"),
  bannerFileId: __t.u64().name("banner_file_id"),
});
