// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddReactionReducer from "../add_reaction_reducer";
import CreateCategoryReducer from "../create_category_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import CreateInviteReducer from "../create_invite_reducer";
import CreateServerReducer from "../create_server_reducer";
import DeleteCategoryReducer from "../delete_category_reducer";
import DeleteChannelReducer from "../delete_channel_reducer";
import DeleteDmMessageReducer from "../delete_dm_message_reducer";
import DeleteFileReducer from "../delete_file_reducer";
import DeleteMessageReducer from "../delete_message_reducer";
import DeleteServerReducer from "../delete_server_reducer";
import JoinDmCallReducer from "../join_dm_call_reducer";
import JoinServerReducer from "../join_server_reducer";
import JoinVoiceChannelReducer from "../join_voice_channel_reducer";
import LeaveDmCallReducer from "../leave_dm_call_reducer";
import LeaveServerReducer from "../leave_server_reducer";
import LeaveVoiceChannelReducer from "../leave_voice_channel_reducer";
import LoginReducer from "../login_reducer";
import LogoutReducer from "../logout_reducer";
import OpenDmThreadReducer from "../open_dm_thread_reducer";
import RegisterReducer from "../register_reducer";
import RemoveAvatarReducer from "../remove_avatar_reducer";
import RemoveBannerReducer from "../remove_banner_reducer";
import RemoveReactionReducer from "../remove_reaction_reducer";
import SendAudioFrameReducer from "../send_audio_frame_reducer";
import SendChannelMessageReducer from "../send_channel_message_reducer";
import SendDmAudioFrameReducer from "../send_dm_audio_frame_reducer";
import SendDmMessageReducer from "../send_dm_message_reducer";
import SendDmVideoFrameReducer from "../send_dm_video_frame_reducer";
import SendVideoFrameReducer from "../send_video_frame_reducer";
import SetChannelMediaSettingsReducer from "../set_channel_media_settings_reducer";
import SetPublicEncryptionKeyReducer from "../set_public_encryption_key_reducer";
import UpdateAvatarReducer from "../update_avatar_reducer";
import UpdateBannerReducer from "../update_banner_reducer";
import UpdateProfileReducer from "../update_profile_reducer";
import UploadFileReducer from "../upload_file_reducer";

export type AddReactionParams = __Infer<typeof AddReactionReducer>;
export type CreateCategoryParams = __Infer<typeof CreateCategoryReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateInviteParams = __Infer<typeof CreateInviteReducer>;
export type CreateServerParams = __Infer<typeof CreateServerReducer>;
export type DeleteCategoryParams = __Infer<typeof DeleteCategoryReducer>;
export type DeleteChannelParams = __Infer<typeof DeleteChannelReducer>;
export type DeleteDmMessageParams = __Infer<typeof DeleteDmMessageReducer>;
export type DeleteFileParams = __Infer<typeof DeleteFileReducer>;
export type DeleteMessageParams = __Infer<typeof DeleteMessageReducer>;
export type DeleteServerParams = __Infer<typeof DeleteServerReducer>;
export type JoinDmCallParams = __Infer<typeof JoinDmCallReducer>;
export type JoinServerParams = __Infer<typeof JoinServerReducer>;
export type JoinVoiceChannelParams = __Infer<typeof JoinVoiceChannelReducer>;
export type LeaveDmCallParams = __Infer<typeof LeaveDmCallReducer>;
export type LeaveServerParams = __Infer<typeof LeaveServerReducer>;
export type LeaveVoiceChannelParams = __Infer<typeof LeaveVoiceChannelReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type LogoutParams = __Infer<typeof LogoutReducer>;
export type OpenDmThreadParams = __Infer<typeof OpenDmThreadReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type RemoveAvatarParams = __Infer<typeof RemoveAvatarReducer>;
export type RemoveBannerParams = __Infer<typeof RemoveBannerReducer>;
export type RemoveReactionParams = __Infer<typeof RemoveReactionReducer>;
export type SendAudioFrameParams = __Infer<typeof SendAudioFrameReducer>;
export type SendChannelMessageParams = __Infer<typeof SendChannelMessageReducer>;
export type SendDmAudioFrameParams = __Infer<typeof SendDmAudioFrameReducer>;
export type SendDmMessageParams = __Infer<typeof SendDmMessageReducer>;
export type SendDmVideoFrameParams = __Infer<typeof SendDmVideoFrameReducer>;
export type SendVideoFrameParams = __Infer<typeof SendVideoFrameReducer>;
export type SetChannelMediaSettingsParams = __Infer<typeof SetChannelMediaSettingsReducer>;
export type SetPublicEncryptionKeyParams = __Infer<typeof SetPublicEncryptionKeyReducer>;
export type UpdateAvatarParams = __Infer<typeof UpdateAvatarReducer>;
export type UpdateBannerParams = __Infer<typeof UpdateBannerReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;
export type UploadFileParams = __Infer<typeof UploadFileReducer>;

